creativity_app/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views


urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="creativity_app/index.html"), name='HomePage'),
    url(r'^catalog/$', views.creativity_catalog, name="MainPage"),
    url(r'^catalog/(?P<subcategory_slug>[-\w]+)/$', views.creativity_catalog, name='SubCategoryCreativeList'),
    url(r'^catalog/(?P<slug>[-\w]+)/(?P<pk>\d+)/$', views.creativity_detail, name="CreativityPage"),
]

order/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

    url(r'^$', views.cart_detail, name='CartDetail'),
    url(r'^remove/(?P<creativity_id>\d+)/$', views.cart_remove, name='CartRemove'),
    url(r'^add/(?P<creativity_id>\d+)/$', views.cart_add, name='CartAdd'),

]

project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include("creativity_app.urls", namespace="creativity_app")),
    url(r'^order/', include('order.urls', namespace='cart')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

creativity_app/models.py
from django.utils import timezone
from django.db import models

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True, unique=True, verbose_name='Название категории')
    slug = models.SlugField(max_length=250, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'


class SubCategory(models.Model):
    category = models.ForeignKey('Category', related_name='subcategory', verbose_name='Категория')
    name = models.CharField(max_length=100, unique=True, verbose_name='Название подкатегории')
    slug = models.SlugField(max_length=250, db_index=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Подкатегория'
        verbose_name_plural = 'Подкатегории'


class Creativity(models.Model):
    subcategory = models.ForeignKey('SubCategory', related_name='creativity', verbose_name='Подкатегория')
    name = models.CharField(max_length=250, unique=True, verbose_name='Название творчества')
    main_photo = models.ImageField(upload_to='media/images/creativity/', verbose_name='Основное фото')
    text = models.TextField(verbose_name='Описание')
    create = models.DateTimeField(default=timezone.now)
    price = models.IntegerField(default=0)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Творчество'
        verbose_name_plural = 'Творчество'


class Album(models.Model):
    creativity = models.ForeignKey('Creativity', related_name='album', verbose_name='Творчество')
    name = models.CharField(max_length=100, verbose_name='Название альбома')

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Альбом'
        verbose_name_plural = 'Альбомы'


class Photo(models.Model):
    album = models.ForeignKey('Album', related_name='photo', verbose_name='Альбом')
    name = models.CharField(max_length=100, verbose_name='Название фото')
    image = models.ImageField(upload_to='media/images/album/', verbose_name='Фото')

    def __str__(self):
        return self.name

order/models.py
from django.db import models

# Create your models here.

order/forms.py
from django.utils import timezone
from django import forms


class OrderForm(forms.Form):
    pass

creativity_app/views.py
from django.shortcuts import render, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist
from order.forms import OrderForm
from .models import Creativity, Category, SubCategory, Album, Photo
# Create your views here.


# TODO: Create new Query for Category/Subcategory/Creativity
def creativity_catalog(request, subcategory_slug=None):
    subcategory = None
    galka = None
    category = Category.objects.all()
    creativities = Creativity.objects.all()
    if subcategory_slug:
        galka = True
        subcategory = get_object_or_404(SubCategory, slug=subcategory_slug)
        creativities = creativities.filter(subcategory=subcategory)
    return render(request, 'creativity_app/balloons.html', {
        'subcategory': subcategory,
        'category': category,
        'creativities': creativities,
        'galka': galka,
    })


def creativity_detail(request, slug, pk):
    creativities = Creativity.objects.all()
    creativity = get_object_or_404(creativities, pk=pk)
    other_offers = creativities.filter(subcategory__slug=slug).exclude(pk=creativity.pk)
    order_form = OrderForm()
    slides = []
    try:
        albums = creativity.album.get(creativity=creativity.pk)
        photos = albums.photo.all()
        for item in photos:
            slides.append(item.image)
    except ObjectDoesNotExist:
        slides = []

    return render(request, 'creativity_app/balloon-page.html', {
        'creativity': creativity,
        'other_offers':  other_offers,
        'slides': slides,
        'slides_count': len(slides),
        'order_form': order_form,
    })

order/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from creativity_app.models import Creativity
from .cart import Cart
from .forms import OrderForm


@require_POST
def cart_add(request, creativity_id):
    cart = Cart(request)
    creativity = get_object_or_404(Creativity, id=creativity_id)
    form = OrderForm(request.POST)
    if form.is_valid():
        cart.add(creativity=creativity)
    return redirect('cart:CartDetail')


def cart_remove(request, creativity_id):
    cart = Cart(request)
    creativity = get_object_or_404(Creativity, id=creativity_id)
    cart.remove(creativity)
    return redirect('cart:CartDetail')


def cart_detail(request):
    cart = Cart(request)

    return render(request, 'cart/detail.html', {'cart': cart})

creativity_app/templates/creativity_app/balloon-page.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<link rel="stylesheet" href="{% static 'css/balloon-page.css' %}">
	<link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.css'>
	<script src="{% static 'js/main.js' %}"></script>
	<script defer src="{%  static 'js/libs/jquery.flexslider.js' %}"></script>
</head>

<body>
	<header>
		<h1><a href="#">ТЕРРИТОРИЯ & ТВОРЧЕСТВА</a></h1>
		<nav>
			<ul>
				<li><a href="{% url "creativity_app:HomePage" %}">Главная</a></li>
				<li><a href="{% url "creativity_app:MainPage" %}">Посмотреть все</a></li>
				<li><a href="#">Блог</a></li>
				<li><a href="#">Контакты</a></li>
				<li><a href="#">Найти</a></li>
			</ul>
		</nav>
		<img src="img/header/header-ballons.png" alt="">
	</header>
	<div class="container">
		<div class="balloon_pic">
			<!-- <img src="img/balloon_pic.jpg" alt=""> -->
			<div class="cont">
				{% if slides_count == 0 %}

                        <img style="width: 125%; margin-left: -20px;" src="{{ creativity.main_photo.url }}" alt="">

                {% else %}

                    <div class="sliderCont">
					<div class="slider slider-for">

						{% for item in slides %}

                            <div><img src="{{ item.url }}" alt=""></div>

                        {% endfor %}

					</div>
					<div class="sliderNavCont">
						<div class="arrw" id="prev">
							<div>
								<img src="{% static "img/arrow.png" %}" alt="">
							</div>
						</div>
						<div class="slider slider-nav">
							{% for item in slides %}

                            <div><img src="{{ item.url }}" alt=""></div>

                            {% endfor %}
						</div>
						<div class="arrw" id="next">
							<div>
								<img src="{% static "img/arrow.png" %}" alt="">
							</div>
						</div>
					</div>
				</div>

                {% endif %}
			</div>
		</div>
		<div class="balloon_desc">
            <div class="balloon_name">{{ creativity.name }}</div>
                <div class="balloon_price">Цена <span>{{ creativity.price }}</span> грн</div>
                <form action="{% url "cart:CartAdd" creativity.id %}" method="post">
                    {% csrf_token %}
                    {{ order_form }}
                    <div class="balloon_order">
{#                    <div class="submit">ЗАКАЗАТЬ</div>#}
                        <input class="submit" type="submit" value="Заказать">
                </div>
                </form>
                <div class="balloon_big_line"></div>
                <div class="balloon_info">{{ creativity.text }}</div>
    {#			<div class="balloon_size">#}
    {#				<div class="desc_title">Размер</div>#}
    {#				<div class="desc_value">44</div>#}
    {#			</div>#}
		</div>
	</div>
	<div class="container">
		<section class="items_rows">

            {% for item in other_offers%}

                <div>
                    <a href="{% url "creativity_app:CreativityPage" slug=item.subcategory.slug pk=item.pk %}">
                        <img src="{{ item.main_photo.url }}" alt="">
                        <div>
                            <div>{{ item.name }}</div>
                            <div>{{ item.price }}</div>
                        </div>
                    </a>
			    </div>

            {% endfor %}

			<div></div>
			<div></div>
			<div></div>
			<div></div>
			<div></div>
		</section>
	</div>
	<footer>
		<h1><a href="#">ballons & flowers</a></h1>
		<nav>
			<ul>
				<li><a href="#">Контакты</a></li>
				<li><a href="#">Шарики</a></li>
				<li><a href="#">Цветы</a></li>
				<li><a href="#">Доставка</a></li>
			</ul>
		</nav>
	</footer>
	
	<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>
	<script src='https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.js'></script>

	<script src="{% static "js/index.js" %}"></script>
</body>

</html>

creativity_app/templates/creativity_app/balloons.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<link rel="stylesheet" href="{% static 'css/balloons.css' %}">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<script defer src="{%  static 'js/libs/jquery.flexslider.js' %}"></script>
</head>
<body>
	<header>
		<h1><a href="#">ТЕРРИТОРИЯ & ТВОРЧЕСТВА</a></h1>
		<nav>
			<ul>
                <li><a href="{% url "creativity_app:HomePage" %}">Главная</a></li>
				<li><a href="{% url "creativity_app:MainPage" %}">Посмотреть все</a></li>
				<li><a href="#">Блог</a></li>
				<li><a href="#">Контакты</a></li>
				<li><a href="#">Найти</a></li>
			</ul>
		</nav>
		<img src="img/header/header-ballons.png" alt="">
	</header>
	<div class="container">
		<aside>
			<ul class="ballons_filter_list">
                <li>
                    <a href="{% url "creativity_app:MainPage" %}">Посмотреть всё</a>
                </li>
				{% for cat in category %}

                    <li>
					<a href="#">{{ cat.name }}</a>
				    	<div class="sublist">
						    <ul>
							    {% for subcat in cat.subcategory.all %}

                                    <li>
                                        <a href="{% url "creativity_app:SubCategoryCreativeList" subcategory_slug=subcat.slug %}">
                                            {{ subcat.name }}
                                        </a>
                                    </li>

							    {% endfor %}

						    </ul>
					    </div>
				    </li>

                {% endfor %}

			</ul>
		</aside>
		<main>
{#			<div class="filter_size">#}
{#				<ul class="ballons_filter_list">#}
{#					<li class="active"><a href="#">Размер 1</a></li>#}
{#					<li><a href="#">Размер 2</a></li>#}
{#					<li><a href="#">Размер 3</a></li>#}
{#					<li><a href="#">Размер 3</a></li>#}
{#					<li><a href="#">Размер 3</a></li>#}
{#				</ul>#}
{#			</div>#}
			<section class="items_rows">

				{% for creative in creativities %}

                    <div>
					<a href="{% url "creativity_app:CreativityPage" pk=creative.pk slug=creative.subcategory.slug %}">
						<img src="{{ creative.main_photo.url }}" alt="{{ creative.name }}">
						<div>
							<div>{{ creative.name|truncatechars:50 }}</div>
							<div>{{ creative.price }}</div>
						</div>
					</a>
				</div>

                {% endfor %}

			</section>
		</main>
	</div>
	<footer>
		<h1><a href="#">ballons & flowers</a></h1>
		<nav>
			<ul>
				<li><a href="#">Контакты</a></li>
				<li><a href="#">Шарики</a></li>
				<li><a href="#">Цветы</a></li>
				<li><a href="#">Доставка</a></li>
			</ul>
		</nav>
	</footer>
</body>
</html>

creativity_app/templates/creativity_app/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<script defer src="{%  static 'js/libs/jquery.flexslider.js' %}"></script>
</head>
<body>
	<header>
		<h1><a href="#">ТЕРРИТОРИЯ & ТВОРЧЕСТВА</a></h1>
		<nav>
			<ul>
                <li><a href="{% url "creativity_app:HomePage" %}">Главная</a></li>
				<li><a href="{% url "creativity_app:MainPage" %}">Посмотреть все</a></li>
				<li><a href="#">Блог</a></li>
				<li><a href="#">Контакты</a></li>
				<li><a href="#">Найти</a></li>
			</ul>
		</nav>
		<img src="img/header/header-ballons.png" alt="">
	</header>
	<div class="main_slider">
{#		<div class="flexslider">#}
{#			<ul class="slides">#}
{#				<li>#}
{#					<a href="#"><img src="{% static "img/btm-cat-1.jpg" %}" /></a>#}
{#				</li>#}
{#				<li>#}
{#					<a href="#"><img src="{% static "img/btm-cat-2.jpg" %}" /></a>#}
{#				</li>#}
{#				<li>#}
{#					<a href="#"><img src="{% static "img/btm-cat-1.jpg" %}" /></a>#}
{#				</li>#}
{#				<li>#}
{#					<a href="#"><img src="{% static "img/btm-cat-2.jpg" %}" /></a>#}
{#				</li>#}
{#			</ul>#}
{#		</div>#}
{#        <div>#}
{#            <br />#}
{#            <br />#}
{#            <br />#}
{#            <br />#}
{#            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Beatae illo illum nihil totam.#}
{#                Earum excepturi modi quis rem ut! Cumque et harum illum, natus necessitatibus porro? Autem non placeat temporibus.</p>#}
{#        </div>#}
	</div>
	<div class="container">
		<section class="bars">
			<div class="pic_block">
				<div class="four_pic">
					<div class="hover">
						<a href="#">
							<img src="{% static "img/bars/top-1.jpg" %}" alt="">
							<img src="{% static "img/bars/top-3.jpg" %}" alt="">
						</a>
					</div>
					<div class="test-i">
						<a href="#">
							<img src="{% static "img/bars/top-2.jpg" %}" alt="">
                            <h2><span>
                                Мыловарение в домашних условиях становится достаточно популярным занятием.>
                                Мыловарение в домашних условиях становится достаточно популярным занятием.
                                Мыловарение в домашних условиях становится достаточно популярным занятием.
                            </span></h2>
						</a>
					</div>
					<div class="test-i">
						<a href="#">
							<img src="{% static "img/bars/top-3.jpg" %}" alt="">
                            <h2><span>
                                Мыловарение в домашних условиях становится достаточно популярным занятием.
                                Мыловарение в домашних условиях становится достаточно популярным занятием.
                                Мыловарение в домашних условиях становится достаточно популярным занятием.
                            </span></h2>
						</a>
					</div>
					<div>
						<a href="#">
							<img src="{% static "img/bars/top-4.jpg" %}" alt="">
						</a>
					</div>
				</div>
				<div class="big_pic">
					<div>
						<a href="#">
							<div class="flexslider">
								<ul class="slides">
									<li>
										<a href="#"><img src="{% static "img/bars/bottom-big.jpg" %}" /></a>
									</li>
									<li>
										<a href="#"><img src="{% static "img/bars/top-big.jpg" %}" /></a>
									</li>
								</ul>
							</div>
						</a>
					</div>
				</div>
			</div>
			<div class="pic_block">
				<div class="big_pic">
					<div>
						<a href="#">
							<img src="{% static "img/bars/bottom-big.jpg" %}" alt="">
						</a>
					</div>
				</div>
				<div class="four_pic">
					<div class="hover">
						<a href="#">
							<img src="{% static "img/bars/bottom-1.jpg" %}" alt="">
							<img src="{% static "img/bars/bottom-3.jpg" %}" alt="">
						</a>
					</div>
					<div class="test-i">
						<a href="#">
							<img src="{% static "img/bars/bottom-2.jpg" %}" alt="">
                            <h2><span>Мыловарение в домашних условиях становится достаточно популярным занятием.</span></h2>
						</a>
					</div>
					<div class="test-i">
						<a href="#">
							<img src="{% static "img/bars/bottom-3.jpg" %}" alt="">
                            <h2><span>Мыловарение в домашних условиях становится достаточно популярным занятием.</span></h2>
						</a>
					</div>
					<div>
						<a href="#">
							<img src="{% static "img/bars/bottom-4.jpg" %}" alt="">
						</a>
					</div>
				</div>
			</div>
		</section>
		<section class="items_rows">
{#			<div>#}
{#				<a href="#">#}
{#					<img src="{% static "img/btm-cat-1.jpg" %}" alt="">#}
{#					<div>#}
{#						<div>Шарик "Сердце"</div>#}
{#						<div>99грн</div>#}
{#					</div>#}
{#				</a>#}
{#			</div>#}
{#			<div>#}
{#				<a href="#">#}
{#					<img src="{% static "img/btm-cat-1.jpg" %}" alt="">#}
{#					<div>#}
{#						<div>Шарик "Сердце"</div>#}
{#						<div>99грн</div>#}
{#					</div>#}
{#				</a>#}
{#			</div>#}
{#			<div>#}
{#				<a href="#">#}
{#					<img src="{% static "img/btm-cat-1.jpg" %}" alt="">#}
{#					<div>#}
{#						<div>Шарик "Сердце"</div>#}
{#						<div>99грн</div>#}
{#					</div>#}
{#				</a>#}
{#			</div>#}
{#			<div>#}
{#				<a href="#">#}
{#					<img src="{% static "img/btm-cat-1.jpg" %}" alt="">#}
{#					<div>#}
{#						<div>Шарик "Сердце"</div>#}
{#						<div>99грн</div>#}
{#					</div>#}
{#				</a>#}
{#			</div>#}
			<div></div>
			<div></div>
			<div></div>
			<div></div>
			<div></div>
		</section>
	</div>
	<footer>
		<h1><a href="#">ballons & flowers</a></h1>
		<nav>
			<ul>
				<li><a href="#">Контакты</a></li>
				<li><a href="#">Шарики</a></li>
				<li><a href="#">Цветы</a></li>
				<li><a href="#">Доставка</a></li>
			</ul>
		</nav>
	</footer>
</body>
</html>

order/templates/cart/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Underwear</title>
    <link rel="stylesheet" href="{% static 'css/reset.css'%}">
	<link rel="stylesheet" href="{% static 'css/styles.css' %}">
	<link rel="stylesheet" href="{% static "css/normalize.css" %}">
	<link rel="stylesheet" href="{% static "css/main_cart.css" %}">
	<link rel="stylesheet" href="{% static "css/cart.css" %}">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="{% static "js/main-cart.js" %}"></script>
	<script src="{% static "js/cart.js" %}"></script>
</head>
<body>
    <header>
		<h1><a href="#">ТЕРРИТОРИЯ & ТВОРЧЕСТВА</a></h1>
		<nav>
			<ul>
				<li><a href="#">Главная</a></li>
				<li><a href="#">Посмотреть все</a></li>
				<li><a href="#">Блог</a></li>
				<li><a href="#">Контакты</a></li>
				<li><a href="#">Найти</a></li>
			</ul>
		</nav>
		<img src="img/header/header-ballons.png" alt="">
	</header>
    <div class="wrapper">
		<div class="busket fll">
			<h1></h1>
			<div class="items_catalog">
				<div class="item_headers fll">
					<div class="item_info_headers fll">
						<div class="header_name">Название</div>
					</div>
					<div class="item_settings_headers fll">
						<div class="header_quantity fll">Количество</div>
						<div class="header_size fll">Размер</div>
						<div class="header_price fll">Цена</div>
					</div>
					<div class="clearfix"></div>
				</div>
				<div class="ordered_item fll">
					{% for item in cart %}

                        <div class="item_info fll">
						<a href="#">
							<div class="small_image fll">
								<img src="{{ item.creative.main_photo.url }}" alt="">
							</div>
							<div class="item_name fll">{{ item.creative.name }}</div>
						</a>
					</div>
					<div class="item_settings fll">
						<div class="item_quantity fll">
							<!-- <input type="number" min="1"> -->
							<span class="minus">
								<img src="http://www.sammy-icon.com/catalog/view/theme/default/image/icon/minus.png" alt="">
							</span>
							<span class="quan_numb">1</span>
							<span class="plus">
								<img src="http://www.sammy-icon.com/catalog/view/theme/default/image/icon/plus.png" alt="">
							</span>
						</div>
						<div class="item_size fll">2</div>
						<div class="item_price fll">
							{{ item.creative.price }}
							<img src="http://www.sammy-icon.com/catalog/view/theme/default/image/icon/esc-img.png" alt="">
						</div>
					</div>

                    {% endfor %}
				</div>

				<div class="clearfix"></div>
{#				<div class="result_price">#}
{#					<div class="summa_text fll">Сумма</div>#}
{#					<div class="summa_price fll">100 рн</div>#}
{#				</div>#}
				<div class="clearfix"></div>
			</div>
		</div>
		<div class="order fll">
			<h1></h1>
{#			<div class="panel delivery">#}
{#				<div class="panel_title">#}
{#					1.Способ доставки#}
{#				</div>#}
{#				<div class="panel_filling">#}
{#					<div class="panel_info_text">#}
{#						Выберите удобный способ доставки для данного заказа#}
{#					</div>#}
{#					<table>#}
{#						<tr>#}
{#							<td><input type="radio" name="shipping" checked></td>#}
{#							<td><img src="http://www.sammy-icon.com/image/icon/novaposhta.novaposhta.png" alt=""></td>#}
{#							<td><span>Новая почта: </span>Доставка по Украине</td>#}
{#							<td>35грн</td>#}
{#						</tr>#}
{#						<tr>#}
{#							<td><input type="radio" name="shipping"></td>#}
{#							<td><img src="https://foodequipment.nethouse.ru/static/img/0000/0005/6570/56570287.rnq980wf53.W665.png" alt=""></td>#}
{#							<td><span>Самовывоз по адресу: </span>Пушкина, 321</td>#}
{#							<td>Бесплатно</td>#}
{#						</tr>#}
{#					</table>#}
{#				</div>#}
{#			</div>#}
			<div class="panel adress">
				<div class="panel_title">
					1.Адрес доставки
				</div>
				<div class="panel_filling">
					<div class="firstname half">
						<input type="text" placeholder="Имя">
					</div>
					<div class="surname half">
						<input type="text" placeholder="Фамилия">
					</div>
					<div class="phone half">
						<input type="phone" placeholder="Телефон">
					</div>
					<div class="email half">
						<input type="email" placeholder="E-Mail">
					</div>
					<div class="adress half">
						<input type="text" placeholder="Адрес">
					</div>
{#					<div class="np_office half">#}
{#						<input type="text" placeholder="Отделение новой почты">#}
{#					</div>#}
				</div>
				<div class="clearfix"></div>
			</div>
{#			<div class="panel pay">#}
{#				<div class="panel_title">#}
{#					3.Способ оплаты#}
{#				</div>#}
{#				<div class="panel_filling">#}
{#					<div class="panel_info_text">#}
{#						Выберите удобный способ доставки для данного заказа#}
{#					</div>#}
{#					<table>#}
{#						<tr>#}
{#							<td><input type="radio" name="pay" checked></td>#}
{#							<td><img src="http://www.sammy-icon.com/image/icon/cod.png" alt=""></td>#}
{#							<td><span>Оплата наличными при доставке</span></td>#}
{#						</tr>#}
{#						<tr>#}
{#							<td><input type="radio" name="pay"></td>#}
{#							<td><img src="http://www.sammy-icon.com/image/icon/liqpay.png" alt=""></td>#}
{#							<td><span>Карта Visa и MasterCard (LiqPay)</span></td>#}
{#						</tr>#}
{#					</table>#}
{#				</div>#}
{#			</div>#}
			<div class="panel order_submit">
				<div class="panel_title">
					2.Подтверждение заказа
				</div>
				<div class="panel_filling">

				    <input type="submit" value="Подтверждение заказа" class="submit_order_button">
			    </div>
		    </div>
		<div class="clearfix"></div>
	</div>

</body>
</html>